env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - import
  - react
settings:
  import/resolver: {node: {extensions: [.jsx, .js]}}
rules:
  # styles
  semi: [1, never]
  camelcase: 1
  comma-style: 1
  no-else-return: 1
  brace-style: [1, stroustrup, {allowSingleLine: true}]
  comma-spacing: 1
  no-nested-ternary: 1

  # syntax/language rules to lil' bugs
  no-self-compare: 1
  no-unused-expressions: [1, {allowShortCircuit: true, allowTernary: true}]
  no-unused-vars: 1
  no-var: 1
  prefer-arrow-callback: 1
  prefer-const: 1
  prefer-spread: 1
  prefer-rest-params: 1 # ... variadic instead of arguments variable
  prefer-template: 1
  no-shadow: [1, {builtinGlobals: false, hoist: all}]
  no-plusplus: 1

  # why would you do these things?
  no-console: 1 # warning, so you can temporarily do it, but shouldn't be in prod code
  no-alert: 2
  no-caller: 2
  no-extend-native: 2
  no-native-reassign: 2
  no-shadow-restricted-names: 1
  no-undefined: 1
  no-array-constructor: 1
  no-new-object: 1

  # react/jsx
  jsx-quotes: 1
  #react/jsx-no-undef: 2
  react/jsx-pascal-case: 1
  react/no-danger: 2
  react/no-deprecated: 2
  react/no-set-state: 2
  react/no-unknown-property: 2
  react/prop-types: 1 # warn if missing proptype restrictions
  # warn if using lazy prop types. go here for more info on non-lazy prop-typing:
  # https://facebook.github.io/react/docs/reusable-components.html
  react/forbid-prop-types: 1
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/react-in-jsx-scope: 2
  react/require-render-return: 2
  react/jsx-key: 2
  react/jsx-no-bind: 1
  react/jsx-no-duplicate-props: 2

  # module imports
  import/no-unresolved: 2
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/no-deprecated: 1
  import/no-extraneous-dependencies: 1
  import/no-commonjs: 1
  import/no-amd: 1
  import/no-nodejs-modules: 1
  import/no-duplicates: 1
  import/extensions: 1
  import/no-namespace: 1
